### PR TITLE
Database configuration changes, Gradle version fix.

### PR DESCRIPTION
**Pull request by dashrath-chauhan**
- Modified testbed backend API code to use system variables for database connection.
- Forced pipeline to use default Gradle version 7.3.3
- Modified AWS secret credentials by @yash-puligundla to execute the pipeline successfully.

### CODE REVIEW

**Comment by yash-puligundla** [comment]
@dashrath-chauhan Thanks for all the work! 
Please add `.idea/` to the `.gitignore` file. I notice that this PR does not contain any AWS template to create RDS and Testbed backend resources. Could you make sure the title of this PR reflects the work in it? 
Additionally, the version on `build.gradle` should be valid i.e., follow semantic versioning. I would keep the version as is and increment it before we make a release on main branch.

**Comment by dashrath-chauhan** [comment]
Hi @yash-puligundla, added .idea and changed versio in build.gradle.
Templates for creating aws resources is in a different directory [here](https://github.com/ga4gh/ga4gh-testbed-api-aws-stack) which we have created initially. Modified the title of PR.

**Comment by yash-puligundla** [comment]
Hi @dashrath-chauhan Please update ".idea" to ".idea/" in the .gitignore file. Its purpose is to prevent all these temp files from showing up on the PR and the repository.

Since the CFT is in a separate repo, I would keep it isolated from the current PR review.

**Review by yash-puligundla — APPROVED** [review]
Looks good!

**Pull request merged**
